### ISSUE TITLE
Uncaught Error: watch $ATOM_HOME ENOSPC

### ISSUE THREAD

**Issue by camlafit** [jccguimaraes/atom-project-viewer#182] opened 2017-11-28 09:27 UTC
**Atom**: 1.22.1 x64
**Electron**: 1.6.15
**OS**: Debian GNU/Linux
**Thrown From**: [project-viewer](https://github.com/jccguimaraes/atom-project-viewer) package 1.2.5

### Stack Trace

Uncaught Error: watch /home/km/.atom ENOSPC

```
At fs.js:1318

Error: watch /home/km/.atom ENOSPC
    at exports._errnoException (util.js:1022:11)
    at FSWatcher.start (fs.js:1316:19)
    at Object.fs.watch (fs.js:1341:11)
    at _directoryWatch (/packages/project-viewer/src/database.js:498:16)
```

### Commands

```
     -0:51.8.0 project-viewer:createNewProject (div.list-item)
```

### Non-Core Packages

```
adwaita-pro-ui 2.1.5 
atom-beautify 0.30.9 
atom-i18n 0.13.0 
atom-ide-ui 0.6.0 
auto-detect-indentation 1.3.0 
auto-encoding 0.7.0 
busy-signal 1.4.3 
color-picker 2.2.5 
docblockr 0.13.2 
git-control 0.9.0 
html-entities 0.4.0 
hyperclick 0.0.0 
ide-php 0.6.10 
intentions 1.1.5 
language-smarty 1.8.0 
project-viewer 1.2.5 
sass-autocompile 0.13.3 
tree-view-git-branch 0.1.2 
tree-view-git-status 1.4.0 
```

**Comment by jccguimaraes** [comment] 2017-12-01 15:21
hey, thanks for reporting this. That is a weird one. Will try to figure it out!

**Comment by jccguimaraes** [comment] 2018-02-03 14:39
Hi @camlafit, just investigated the code in the error which says

> ENOSPC means that there is no space on the drive.

Maybe reading this [stackoverflow](https://stackoverflow.com/questions/22475849/node-js-error-enospc/32600959#32600959).

Will close this.

**Closed by jccguimaraes** 2018-02-03 14:39 UTC
Labels: type: bug

**Comment by camlafit** [comment] 2018-02-05 10:42
Hello

Ok I don't remember how was my hard disk at this moment. If I reproduce it, I'll check this part.
Thanks to have give a look.

**Comment by kraeml** [comment] 2018-03-01 06:18
Why closed? The error still exists. I have 315G free space on disk. ProjektViewer will not start.

**Comment by jccguimaraes** [comment] 2018-03-17 16:02
@kraeml sorry for closing this, but the issue is not related to the package. As it tries to create a file in atom's directory could be that is related with permissions.

**Comment by kraeml** [comment] 2018-04-05 06:56
I understand your answer but in my case the permission in ~/.atom is set for me and the diskspace is enough. I like your project-viewer and I miss it. But it will not run on my system and I don't know why?

What I do was:
```
sudo chown -R michl: ~/.atom

df -h /home
Dateisystem    Größe Benutzt Verf. Verw% Eingehängt auf
/dev/sda4       401G    127G  275G   32% /home

```

When I start atom this message pop up:

[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.24.1 x64
**Electron**: 1.6.16
**OS**: Ubuntu 17.10
**Thrown From**: [project-viewer](https://github.com/jccguimaraes/atom-project-viewer) package 1.3.0


### Stack Trace

Failed to activate the project-viewer package

```
At watch /home/michl/.atom ENOSPC

Error: watch /home/michl/.atom ENOSPC
    at exports._errnoException (util.js:1022:11)
    at FSWatcher.start (fs.js:1316:19)
    at Object.fs.watch (fs.js:1341:11)
    at _directoryWatch (/packages/project-viewer/src/database.js:498:16)
    at /packages/project-viewer/src/database.js:446:3)
    at /packages/project-viewer/src/main.js:41:12)
    at Package.activateNow (/opt/atom/resources/app/src/package.js:230:33)
    at measure (/opt/atom/resources/app/src/package.js:206:33)
    at Package.measure (/opt/atom/resources/app/src/package.js:88:25)
    at activationPromise.Promise (/opt/atom/resources/app/src/package.js:200:20)
    at Package.activate (/opt/atom/resources/app/src/package.js:198:38)
    at PackageManager.activatePackage (/opt/atom/resources/app/src/package-manager.js:695:42)
    at /opt/atom/resources/app/node_modules/settings-view/lib/package-manager.js:535:35
    at exit (/opt/atom/resources/app/node_modules/settings-view/lib/package-manager.js:128:22)
    at triggerExitCallback (/opt/atom/resources/app/src/buffered-process.js:338:17)
    at /opt/atom/resources/app/src/buffered-process.js:359:17
    at Socket.<anonymous> (/opt/atom/resources/app/src/buffered-process.js:220:15)
    at emitOne (events.js:101:20)
    at Socket.emit (events.js:188:7)
    at Pipe._handle.close [as _onclose] (net.js:501:12)
```

### Commands

```
     -8:00.7.0 core:confirm (input.hidden-input)
```

### Non-Core Packages

```
ansible-snippets 0.2.0 
atom-beautify 0.32.2 
atom-ide-ui 0.9.4 
autocomplete-ansible 0.1.19 
busy-signal 1.4.3 
editorconfig 2.2.2 
file-icons 2.1.18 
go-plus 5.8.3 
intentions 1.1.5 
linter 2.2.0 
linter-ui-default 1.7.1 
minimap 4.29.8 
open-in-browser 0.5.2 
platformio-ide-terminal 2.8.1 
project-manager 3.3.5 
project-viewer 1.3.0 
remote-atom 1.3.12 
```

I wondering about `/packages/project-viewer/src/database.js` this directory not exists. But `~/.atom/packages/project-viewer/src/database.js` exists.

**Comment by jccguimaraes** [comment] 2018-04-05 08:02
hey @kraeml 

I will try to have a more in depth understanding of this. Will do my best to help in this weird cenario.

Thanks for the ❤️ to this package.

**Comment by chrisgavin** [comment] 2018-04-05 12:53
As far as I can tell, this is not due to an actual lack of disk space, but due to a lack of inotify watches.

I increased my user watch limit and the problem went away for me.

**Comment by kraeml** [comment] 2018-04-05 13:49
@chrisgavin Thanks that did the job. Here my temporarily solution:
```
cat /proc/sys/fs/inotify/max_user_watches 
8192
sudo sysctl fs.inotify.max_user_watches=524288
fs.inotify.max_user_watches = 524288
```
Restart atom.io and project-viewer is running.

@jccguimaraes You are welcome. Thanks for your work.

**Comment by kraeml** [comment] 2018-04-05 13:59
Here my solution
```
echo fs.inotify.max_user_watches=16384 | sudo tee -a /etc/sysctl.conf
sudo sysctl -p
cat /proc/sys/fs/inotify/max_user_watches
```
Found here https://askubuntu.com/questions/770374/user-limit-of-inotify-watches-reached-on-ubuntu-16-04/770381

When changed back to 8192 the error ENOSPC comes back.
