### ISSUE TITLE
Panel Controls Not Working

### ISSUE THREAD

**Issue by vastsoun** [jccguimaraes/atom-project-viewer#173] opened 2017-10-14 00:37 UTC
# Issue
PV works from the PV panel (i.e. changing projects), but closing and opening the panel does not work at all --> neither does ctrl-shift-alt-v nor from the atom-->pakcages-->Project Viewer menu.

## Environment
- Ubuntu
-  Atom 1.21
- tested with all other atom packages disabled

## Steps
Just install project viewer with atom 1.21.

**Comment by jccguimaraes** [comment] 2017-10-14 09:44
hi @vastsoun,

thanks for reporting, will have a look at it

**Comment by jccguimaraes** [comment] 2017-10-17 02:07
hi @vastsoun,

Just been testing this and can't reproduce, can you try to give more intel?
Also hit `cmd+.` and try to see if nothing is overriding the command `ctrl-shift-alt-v`.

Although choosing `Toggle Panel` from the `Settings -> Project-Viewer` should work.

Can you confirm or not all of this?

Thanks

**Comment by jccguimaraes** [comment] 2017-10-29 00:58
closing as no more feedback

**Closed** 2017-10-29 00:58 UTC
Labels: action: discussion, action: investigation
