### ISSUE TITLE
Database not found after update

### ISSUE THREAD

**Issue by asitemade4u** [jccguimaraes/atom-project-viewer#115] opened 2017-02-13 14:14 UTC
# ISSUE
The updates to version 1.0.0 then version 1.0.1 have taken place.
But when I open Project Viewer again, a message tells the project database cannot be found and no project is displayed.
How can I recover them?

## Environment
- **OS**: Ubuntu 16.04 LTS;
- **Atom**: 1.41.1;

**Comment by jccguimaraes** [comment] 2017-02-13 14:17
please go to `menu -> Project-Viewer -> Utilities -> Convert from 0.3.x ...`

Please inform me if this resolves, it is actually not a bug, but something i don't want the project to automatically do

**Comment by jccguimaraes** [comment] 2017-02-13 15:33
Please update to `1.0.3` sorry about this...

**Comment by devnox** [comment] 2017-02-13 16:11
Im currently using 1.0.3 version and its not working. I tried to Convert from 0.3.x and still nothing. Please advice.

**Comment by girlandhercode** [comment] 2017-02-13 16:15
First: Thank you for all of the work that went into this package. It is fantastic.

The upgrade may or may not have solved the original issue, however, I still had to toggle "Disable" for the package and then re-"Enable" it to get the project sidebar to show up. My project list and all info is still there, however it will not show up at all without the toggling of the package state.  I'll post my error in a new issue.

**Comment by jccguimaraes** [comment] 2017-02-13 16:44
@devnox let me check this issue. I have two guys here that migrated well.
Can you check if you really have the file like `~/.atom/storage/project-viewer.json`?

**Comment by jccguimaraes** [comment] 2017-02-13 16:45
@girlandhercode does in config you have `Display On Startup` and `Panel visibility interaction state` checked?

**Comment by girlandhercode** [comment] 2017-02-13 17:14
@jccguimaraes These are my settings:
![image](https://cloud.githubusercontent.com/assets/2183606/22894120/ec832776-f1e5-11e6-979b-3db25c3690c4.png)

**Comment by jccguimaraes** [comment] 2017-02-13 17:24
@girlandhercode thank you for the feedback, let me see this later tonight. This was a major refactor. Didn't expect all these issues :) :( let's see.

Appreciate the patience... :full_moon_with_face:

**Comment by jccguimaraes** [comment] 2017-02-13 19:13
@girlandhercode, made two fixes, can you check? if not, do you have `tree-view` active? thankx

**Comment by girlandhercode** [comment] 2017-02-13 19:28
@jccguimaraes I still have to toggle "Disable" then re-"Enable" the package to get the sidebar to show up, however, I am no longer experiencing #118 either so progress is good!!

I have tried the following:

- going to "Packages" -> "Project Viewer" -> "Toggle Panel" 
-  opening Atom's command pallet ( `ctrl`-`shift`-`p` ) and selecting "Project Viewer: TogglePanel"
-  The project viewer default keybind ( `ctrl`-`alt`-`shift`-`v` ) 

None of the above open the panel (nor does the command pallet allow me to switch between projects). Toggling package state makes the panel show up.

Thanks again!

**Comment by jccguimaraes** [comment] 2017-02-13 19:31
will investigate more

**Comment by devnox** [comment] 2017-02-13 20:32
@jccguimaraes yes i have ~/.atom/storage/project-viewer.json

**Comment by devnox** [comment] 2017-02-13 20:33
I get that error:

> Local database corrupted.
> Please check the content of the local database.

**Comment by jccguimaraes** [comment] 2017-02-13 20:57
@devnox, i know it is asking too much but can you PM your file? prob if you have gist of it (dont use import/export for now if you have this issue)

**Comment by devnox** [comment] 2017-02-13 20:59
Hey I just found something. I moved the panel to the right side position and after that moved it to the left side without Auto hidding. I think there is something in Auto Hidding option.

**Comment by philip-hodder** [comment] 2017-02-13 22:52
I also get the database corruption error. This is with 1.0.4.

**Comment by devnox** [comment] 2017-02-14 14:02
After last update I again can not see my projects.

**Comment by jccguimaraes** [comment] 2017-02-14 14:38
@devnox and @philip-hodder, using the utilities -> migrate from `0.3.x` don't work i really don't know why you can't get it to work. 
Just for troubleshooting, you came from a `0.3.x` and not `0.2.x` right?

Any ways,  if you can send a snippet of the file in PM that would be great also. I am really sorry for this :(

**Comment by colorful-tones** [comment] 2017-02-14 17:54
I've been away from my computer (unusual) for a few days and just updating all the things in Atom and got the error message:

> Local database corrupted.
> Please check the content of the local database.

I perused this ticket, and then did the following steps in exact sequence:

1. `menu -> Project-Viewer -> Utilities -> Convert from 0.3.x`
2. `Disabled` Project Viewer package
3. `Enabled` Project Viewer package
4. Restarted Atom
5. The sidebar projects were restored and no longer receiving `Local database corrupted.` error.
However, the sidebar setting for Autohide was not restored, therefore I just had to...
6. Go to Project Viewer Settings and re-check the "Sidebar auto hiding" option.
7. Another restart of Atom and back to where I was, and no errors. Seems good to go now.

Atom: 1.14.1
Project Viewer: 1.0.5

**Comment by jccguimaraes** [comment] 2017-02-14 17:57
@colorful-tones, thanks for this feedback, i hope it can solve some issues for the short run, i will be diving all of this and hopefully come to a final solution. i have identified the issues regarding the auto hide at least but it is not a simple fix due to the major refactor i did. sorry :D

**Comment by philip-hodder** [comment] 2017-02-14 18:18
Running the "Utilities > Convert from 0.3.x" tool worked great! I think this should maybe be at the top of the readme file, at least for a few releases! Other than that this seems to be an excellent update! Thanks!

**Comment by jccguimaraes** [comment] 2017-02-14 18:28
@philip-hodder, thank god! just missing now for @devnox to work :( thank you for the vote of confidence on the update. there were a lot of changes, and there is still some big ass issues.

**Comment by devnox** [comment] 2017-02-15 08:38
Hello again.
The problem here is that the Auto hiding is not working properly. When I enabled the auto hiding feature the panel is not hidding, only the projects disapear but project viewer panel stays on and empty.

**Comment by jccguimaraes** [comment] 2017-02-15 08:41
it is almost ready the autohide! just hang there people :(

**Comment by jccguimaraes** [comment] 2017-02-15 11:21
can you all please validate with `1.0.6` is this issue is resolved?

**Comment by devnox** [comment] 2017-02-15 11:42
It is getting better. Now anytime i start Atom i need to Toggle Panel to get it working.

**Comment by jccguimaraes** [comment] 2017-02-15 11:44
@devnox what are the 2 and 3 option of the pv config. by the way, you recovered your DB?

**Comment by devnox** [comment] 2017-02-15 11:48
Yeah Database is recovered.
I'm attaching a screenshot of what I have.
![pv-conf](https://cloud.githubusercontent.com/assets/1416251/22973126/6b97c5d0-f385-11e6-9155-cadf9ebe00e1.jpg)

**Comment by jccguimaraes** [comment] 2017-02-15 11:51
@devnox, there you have. 2nd and 3rd option are related. `Display on startup` -> you need to check the 3rd. so it is displayed on startup.

**Comment by devnox** [comment] 2017-02-15 13:08
Just great! Its working now!

**Comment by jccguimaraes** [comment] 2017-02-15 13:12
@devnox. cool

**Comment by jccguimaraes** [comment] 2017-02-15 13:27
closing this issue if you all don't mind... :+1:

**Closed by jccguimaraes** 2017-02-15 13:27 UTC
Labels: info: MUST READ

**Comment by devcline** [comment] 2019-03-12 15:55
hello, i had a similar error today. After my researches. in the file _project-viewer.json_ at the end there was a one more than necessary symbol `}` how he get there , i dont have idea. Maybe it helps someone.
